using System;
using System.CodeDom.Compiler;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using DBDataLibrary.Attributes;
using DBDataLibrary.CRUD;

namespace DBDataTables.Tables
{
    //  <auto-generated>
    //   -------------------------------------------------- 
    //  |               AUTO-GENERATED CLASS               |
    //  |           -- DO NOT MODIFY MANUALLY! --          |
    //  |  ANY CHANGE WILL BE LOST AT THE NEXT GENERATION  |
    //   -------------------------------------------------- 
    //  </auto-generated>
    [TableName("MFC_CONV_STRETCHER")]
    [GeneratedCode("DbDataClassGenerator", "1.0.0.0")]
    public partial class MfcConvStretcher : ACrudBase<MfcConvStretcher>
    {
        public MfcConvStretcher() : base() { }
        
        [NonSerialized] private string _cdItem = "";
        [ColumnName("CD_ITEM")]
        public string CdItem
        {
            get => _cdItem;
            set
            {
                if (!Equals(_cdItem, value))
                {
                    _cdItem = value;
                    AddModifiedProperty(nameof(CdItem));
                }
            }
        }

        [NonSerialized] private int? _flStatus;
        [ColumnName("FL_STATUS")]
        public int? FlStatus
        {
            get => _flStatus;
            set
            {
                if (!Equals(_flStatus, value))
                {
                    _flStatus = value;
                    AddModifiedProperty(nameof(FlStatus));
                }
            }
        }

    }
}
