using System;
using System.CodeDom.Compiler;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using DBDataLibrary.Attributes;
using DBDataLibrary.CRUD;

namespace DBDataTables.Tables
{
    //  <auto-generated>
    //   -------------------------------------------------- 
    //  |               AUTO-GENERATED CLASS               |
    //  |           -- DO NOT MODIFY MANUALLY! --          |
    //  |  ANY CHANGE WILL BE LOST AT THE NEXT GENERATION  |
    //   -------------------------------------------------- 
    //  </auto-generated>
    [TableName("MFC_CONV_MAX_HEIGHT")]
    [GeneratedCode("DbDataClassGenerator", "1.0.0.0")]
    public partial class MfcConvMaxHeight : ACrudBase<MfcConvMaxHeight>
    {
        public MfcConvMaxHeight() : base() { }
        
        [NonSerialized] private string _itemStart = "";
        [ColumnName("ITEM_START")]
        public string ItemStart
        {
            get => _itemStart;
            set
            {
                if (!Equals(_itemStart, value))
                {
                    _itemStart = value;
                    AddModifiedProperty(nameof(ItemStart));
                }
            }
        }

        [NonSerialized] private string _itemDest = "";
        [ColumnName("ITEM_DEST")]
        public string ItemDest
        {
            get => _itemDest;
            set
            {
                if (!Equals(_itemDest, value))
                {
                    _itemDest = value;
                    AddModifiedProperty(nameof(ItemDest));
                }
            }
        }

        [NonSerialized] private string _cdParameter = "";
        [ColumnName("CD_PARAMETER")]
        public string CdParameter
        {
            get => _cdParameter;
            set
            {
                if (!Equals(_cdParameter, value))
                {
                    _cdParameter = value;
                    AddModifiedProperty(nameof(CdParameter));
                }
            }
        }

    }
}
