using System;
using System.CodeDom.Compiler;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using DBDataLibrary.Attributes;
using DBDataLibrary.CRUD;

namespace DBDataTables.Tables
{
    //  <auto-generated>
    //   -------------------------------------------------- 
    //  |               AUTO-GENERATED CLASS               |
    //  |           -- DO NOT MODIFY MANUALLY! --          |
    //  |  ANY CHANGE WILL BE LOST AT THE NEXT GENERATION  |
    //   -------------------------------------------------- 
    //  </auto-generated>
    [TableName("MFC_CONV_GROUP_COLDSTART")]
    [GeneratedCode("DbDataClassGenerator", "1.0.0.0")]
    public partial class MfcConvGroupColdstart : ACrudBase<MfcConvGroupColdstart>
    {
        public MfcConvGroupColdstart() : base() { }
        
        [NonSerialized] private string _cdGroup = "";
        [ColumnName("CD_GROUP")]
        [Required]
        public string CdGroup
        {
            get => _cdGroup;
            set
            {
                if (!Equals(_cdGroup, value))
                {
                    _cdGroup = value;
                    AddModifiedProperty(nameof(CdGroup));
                }
            }
        }

        [NonSerialized] private string _cdStation = "";
        [ColumnName("CD_STATION")]
        [Required]
        public string CdStation
        {
            get => _cdStation;
            set
            {
                if (!Equals(_cdStation, value))
                {
                    _cdStation = value;
                    AddModifiedProperty(nameof(CdStation));
                }
            }
        }

    }
}
