using System;
using System.CodeDom.Compiler;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using DBDataLibrary.Attributes;
using DBDataLibrary.CRUD;

namespace DBDataTables.Tables
{
    //  <auto-generated>
    //   -------------------------------------------------- 
    //  |               AUTO-GENERATED CLASS               |
    //  |           -- DO NOT MODIFY MANUALLY! --          |
    //  |  ANY CHANGE WILL BE LOST AT THE NEXT GENERATION  |
    //   -------------------------------------------------- 
    //  </auto-generated>
    [TableName("MFC_CONV_DECODE_DESTINATION")]
    [GeneratedCode("DbDataClassGenerator", "1.0.0.0")]
    public partial class MfcConvDecodeDestination : ACrudBase<MfcConvDecodeDestination>
    {
        public MfcConvDecodeDestination() : base() { }
        
        [NonSerialized] private int _destType = default(int);
        [ColumnName("DEST_TYPE")]
        [Key]
        public int DestType
        {
            get => _destType;
            set
            {
                if (!Equals(_destType, value))
                {
                    _destType = value;
                    AddModifiedProperty(nameof(DestType));
                }
            }
        }

        [NonSerialized] private int _destPar = default(int);
        [ColumnName("DEST_PAR")]
        [Key]
        public int DestPar
        {
            get => _destPar;
            set
            {
                if (!Equals(_destPar, value))
                {
                    _destPar = value;
                    AddModifiedProperty(nameof(DestPar));
                }
            }
        }

        [NonSerialized] private string _cdItem = "";
        [ColumnName("CD_ITEM")]
        [Key]
        public string CdItem
        {
            get => _cdItem;
            set
            {
                if (!Equals(_cdItem, value))
                {
                    _cdItem = value;
                    AddModifiedProperty(nameof(CdItem));
                }
            }
        }

    }
}
