using System;
using System.CodeDom.Compiler;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using DBDataLibrary.Attributes;
using DBDataLibrary.CRUD;

namespace DBDataTables.Tables
{
    //  <auto-generated>
    //   -------------------------------------------------- 
    //  |               AUTO-GENERATED CLASS               |
    //  |           -- DO NOT MODIFY MANUALLY! --          |
    //  |  ANY CHANGE WILL BE LOST AT THE NEXT GENERATION  |
    //   -------------------------------------------------- 
    //  </auto-generated>
    [TableName("MFC_CONV_UDM_TYPE")]
    [GeneratedCode("DbDataClassGenerator", "1.0.0.0")]
    public partial class MfcConvUdmType : ACrudBase<MfcConvUdmType>
    {
        public MfcConvUdmType() : base() { }
        
        [NonSerialized] private long _oid = default(long);
        [ColumnName("OID")]
        [Key]
        public long Oid
        {
            get => _oid;
            set
            {
                if (!Equals(_oid, value))
                {
                    _oid = value;
                    AddModifiedProperty(nameof(Oid));
                }
            }
        }

        [NonSerialized] private long? _oidProperty;
        [ColumnName("OID_PROPERTY")]
        public long? OidProperty
        {
            get => _oidProperty;
            set
            {
                if (!Equals(_oidProperty, value))
                {
                    _oidProperty = value;
                    AddModifiedProperty(nameof(OidProperty));
                }
            }
        }

        [NonSerialized] private int _tpUdm = default(int);
        [ColumnName("TP_UDM")]
        [Required]
        public int TpUdm
        {
            get => _tpUdm;
            set
            {
                if (!Equals(_tpUdm, value))
                {
                    _tpUdm = value;
                    AddModifiedProperty(nameof(TpUdm));
                }
            }
        }

        [NonSerialized] private string _idUdm = "";
        [ColumnName("ID_UDM")]
        [Required]
        public string IdUdm
        {
            get => _idUdm;
            set
            {
                if (!Equals(_idUdm, value))
                {
                    _idUdm = value;
                    AddModifiedProperty(nameof(IdUdm));
                }
            }
        }

        [NonSerialized] private string _dscUdm = "";
        [ColumnName("DSC_UDM")]
        [Required]
        public string DscUdm
        {
            get => _dscUdm;
            set
            {
                if (!Equals(_dscUdm, value))
                {
                    _dscUdm = value;
                    AddModifiedProperty(nameof(DscUdm));
                }
            }
        }

        [NonSerialized] private int _width = default(int);
        [ColumnName("WIDTH")]
        [Required]
        public int Width
        {
            get => _width;
            set
            {
                if (!Equals(_width, value))
                {
                    _width = value;
                    AddModifiedProperty(nameof(Width));
                }
            }
        }

        [NonSerialized] private int _length = default(int);
        [ColumnName("LENGTH")]
        [Required]
        public int Length
        {
            get => _length;
            set
            {
                if (!Equals(_length, value))
                {
                    _length = value;
                    AddModifiedProperty(nameof(Length));
                }
            }
        }

        [NonSerialized] private int? _weight;
        [ColumnName("WEIGHT")]
        public int? Weight
        {
            get => _weight;
            set
            {
                if (!Equals(_weight, value))
                {
                    _weight = value;
                    AddModifiedProperty(nameof(Weight));
                }
            }
        }

        [NonSerialized] private int? _lenX;
        [ColumnName("LEN_X")]
        public int? LenX
        {
            get => _lenX;
            set
            {
                if (!Equals(_lenX, value))
                {
                    _lenX = value;
                    AddModifiedProperty(nameof(LenX));
                }
            }
        }

        [NonSerialized] private int? _lenY;
        [ColumnName("LEN_Y")]
        public int? LenY
        {
            get => _lenY;
            set
            {
                if (!Equals(_lenY, value))
                {
                    _lenY = value;
                    AddModifiedProperty(nameof(LenY));
                }
            }
        }

        [NonSerialized] private int? _lenZ;
        [ColumnName("LEN_Z")]
        public int? LenZ
        {
            get => _lenZ;
            set
            {
                if (!Equals(_lenZ, value))
                {
                    _lenZ = value;
                    AddModifiedProperty(nameof(LenZ));
                }
            }
        }

        [NonSerialized] private int? _maxWeight;
        [ColumnName("MAX_WEIGHT")]
        public int? MaxWeight
        {
            get => _maxWeight;
            set
            {
                if (!Equals(_maxWeight, value))
                {
                    _maxWeight = value;
                    AddModifiedProperty(nameof(MaxWeight));
                }
            }
        }

        [NonSerialized] private int? _tare;
        [ColumnName("TARE")]
        public int? Tare
        {
            get => _tare;
            set
            {
                if (!Equals(_tare, value))
                {
                    _tare = value;
                    AddModifiedProperty(nameof(Tare));
                }
            }
        }

        [NonSerialized] private int? _doubleDepth;
        [ColumnName("DOUBLE_DEPTH")]
        public int? DoubleDepth
        {
            get => _doubleDepth;
            set
            {
                if (!Equals(_doubleDepth, value))
                {
                    _doubleDepth = value;
                    AddModifiedProperty(nameof(DoubleDepth));
                }
            }
        }

        [NonSerialized] private string _tpUdmHost = "";
        [ColumnName("TP_UDM_HOST")]
        public string TpUdmHost
        {
            get => _tpUdmHost;
            set
            {
                if (!Equals(_tpUdmHost, value))
                {
                    _tpUdmHost = value;
                    AddModifiedProperty(nameof(TpUdmHost));
                }
            }
        }

        [NonSerialized] private string _dscUdmRf = "";
        [ColumnName("DSC_UDM_RF")]
        public string DscUdmRf
        {
            get => _dscUdmRf;
            set
            {
                if (!Equals(_dscUdmRf, value))
                {
                    _dscUdmRf = value;
                    AddModifiedProperty(nameof(DscUdmRf));
                }
            }
        }

        [NonSerialized] private int? _tpUdmPlc;
        [ColumnName("TP_UDM_PLC")]
        public int? TpUdmPlc
        {
            get => _tpUdmPlc;
            set
            {
                if (!Equals(_tpUdmPlc, value))
                {
                    _tpUdmPlc = value;
                    AddModifiedProperty(nameof(TpUdmPlc));
                }
            }
        }

        [NonSerialized] private string _cdLanguage = "";
        [ColumnName("CD_LANGUAGE")]
        public string CdLanguage
        {
            get => _cdLanguage;
            set
            {
                if (!Equals(_cdLanguage, value))
                {
                    _cdLanguage = value;
                    AddModifiedProperty(nameof(CdLanguage));
                }
            }
        }

        [NonSerialized] private int? _height;
        [ColumnName("HEIGHT")]
        public int? Height
        {
            get => _height;
            set
            {
                if (!Equals(_height, value))
                {
                    _height = value;
                    AddModifiedProperty(nameof(Height));
                }
            }
        }

    }
}
