using System;
using System.CodeDom.Compiler;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using DBDataLibrary.Attributes;
using DBDataLibrary.CRUD;

namespace DBDataTables.Tables
{
    //  <auto-generated>
    //   -------------------------------------------------- 
    //  |               AUTO-GENERATED CLASS               |
    //  |           -- DO NOT MODIFY MANUALLY! --          |
    //  |  ANY CHANGE WILL BE LOST AT THE NEXT GENERATION  |
    //   -------------------------------------------------- 
    //  </auto-generated>
    [TableName("MFC_CONV_LIFT_MISSIONS")]
    [GeneratedCode("DbDataClassGenerator", "1.0.0.0")]
    public partial class MfcConvLiftMissions : ACrudBase<MfcConvLiftMissions>
    {
        public MfcConvLiftMissions() : base() { }
        
        [NonSerialized] private int _cdLift = default(int);
        [ColumnName("CD_LIFT")]
        [Required]
        public int CdLift
        {
            get => _cdLift;
            set
            {
                if (!Equals(_cdLift, value))
                {
                    _cdLift = value;
                    AddModifiedProperty(nameof(CdLift));
                }
            }
        }

        [NonSerialized] private int _tpMission = default(int);
        [ColumnName("TP_MISSION")]
        [Required]
        public int TpMission
        {
            get => _tpMission;
            set
            {
                if (!Equals(_tpMission, value))
                {
                    _tpMission = value;
                    AddModifiedProperty(nameof(TpMission));
                }
            }
        }

        [NonSerialized] private long? _oidUdm;
        [ColumnName("OID_UDM")]
        public long? OidUdm
        {
            get => _oidUdm;
            set
            {
                if (!Equals(_oidUdm, value))
                {
                    _oidUdm = value;
                    AddModifiedProperty(nameof(OidUdm));
                }
            }
        }

        [NonSerialized] private string _source = "";
        [ColumnName("SOURCE")]
        [Required]
        public string Source
        {
            get => _source;
            set
            {
                if (!Equals(_source, value))
                {
                    _source = value;
                    AddModifiedProperty(nameof(Source));
                }
            }
        }

        [NonSerialized] private string _dest = "";
        [ColumnName("DEST")]
        [Required]
        public string Dest
        {
            get => _dest;
            set
            {
                if (!Equals(_dest, value))
                {
                    _dest = value;
                    AddModifiedProperty(nameof(Dest));
                }
            }
        }

        [NonSerialized] private int _counter = default(int);
        [ColumnName("COUNTER")]
        [Required]
        public int Counter
        {
            get => _counter;
            set
            {
                if (!Equals(_counter, value))
                {
                    _counter = value;
                    AddModifiedProperty(nameof(Counter));
                }
            }
        }

        [NonSerialized] private int _running = default(int);
        [ColumnName("RUNNING")]
        [Required]
        public int Running
        {
            get => _running;
            set
            {
                if (!Equals(_running, value))
                {
                    _running = value;
                    AddModifiedProperty(nameof(Running));
                }
            }
        }

        [NonSerialized] private int _enable = default(int);
        [ColumnName("ENABLE")]
        [Required]
        public int Enable
        {
            get => _enable;
            set
            {
                if (!Equals(_enable, value))
                {
                    _enable = value;
                    AddModifiedProperty(nameof(Enable));
                }
            }
        }

        [NonSerialized] private int _priority = default(int);
        [ColumnName("PRIORITY")]
        [Required]
        public int Priority
        {
            get => _priority;
            set
            {
                if (!Equals(_priority, value))
                {
                    _priority = value;
                    AddModifiedProperty(nameof(Priority));
                }
            }
        }

        [NonSerialized] private int _stMission = default(int);
        [ColumnName("ST_MISSION")]
        [Required]
        public int StMission
        {
            get => _stMission;
            set
            {
                if (!Equals(_stMission, value))
                {
                    _stMission = value;
                    AddModifiedProperty(nameof(StMission));
                }
            }
        }

        [NonSerialized] private string _liftItem = "";
        [ColumnName("LIFT_ITEM")]
        [Required]
        public string LiftItem
        {
            get => _liftItem;
            set
            {
                if (!Equals(_liftItem, value))
                {
                    _liftItem = value;
                    AddModifiedProperty(nameof(LiftItem));
                }
            }
        }

        [NonSerialized] private DateTime _dtInsertMission = DateTime.MinValue;
        [ColumnName("DT_INSERT_MISSION")]
        [Required]
        public DateTime DtInsertMission
        {
            get => _dtInsertMission;
            set
            {
                if (!Equals(_dtInsertMission, value))
                {
                    _dtInsertMission = value;
                    AddModifiedProperty(nameof(DtInsertMission));
                }
            }
        }

        [NonSerialized] private DateTime? _dtStartMission;
        [ColumnName("DT_START_MISSION")]
        public DateTime? DtStartMission
        {
            get => _dtStartMission;
            set
            {
                if (!Equals(_dtStartMission, value))
                {
                    _dtStartMission = value;
                    AddModifiedProperty(nameof(DtStartMission));
                }
            }
        }

        [NonSerialized] private DateTime? _dtUpdateMission;
        [ColumnName("DT_UPDATE_MISSION")]
        public DateTime? DtUpdateMission
        {
            get => _dtUpdateMission;
            set
            {
                if (!Equals(_dtUpdateMission, value))
                {
                    _dtUpdateMission = value;
                    AddModifiedProperty(nameof(DtUpdateMission));
                }
            }
        }

    }
}
