using System;
using System.CodeDom.Compiler;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using DBDataLibrary.Attributes;
using DBDataLibrary.CRUD;

namespace DBDataLibrary.Tables
{
    //  <auto-generated>
    //   -------------------------------------------------- 
    //  |               AUTO-GENERATED CLASS               |
    //  |           -- DO NOT MODIFY MANUALLY! --          |
    //  |  ANY CHANGE WILL BE LOST AT THE NEXT GENERATION  |
    //   -------------------------------------------------- 
    //  </auto-generated>
    [TableName("MFC_CONV_MOVEMENTS")]
    [GeneratedCode("DbDataClassGenerator", "1.0.0.0")]
    public partial class MfcConvMovements : ACrudBase<MfcConvMovements>
    {
        public MfcConvMovements() : base() { }
        
        [NonSerialized] private long _oid = default(long);
        [ColumnName("OID")]
        [Key]
        public long Oid
        {
            get => _oid;
            set
            {
                if (!Equals(_oid, value))
                {
                    _oid = value;
                    AddModifiedProperty(nameof(Oid));
                }
            }
        }

        [NonSerialized] private long? _oidUdm;
        [ColumnName("OID_UDM")]
        public long? OidUdm
        {
            get => _oidUdm;
            set
            {
                if (!Equals(_oidUdm, value))
                {
                    _oidUdm = value;
                    AddModifiedProperty(nameof(OidUdm));
                }
            }
        }

        [NonSerialized] private int? _startType;
        [ColumnName("START_TYPE")]
        public int? StartType
        {
            get => _startType;
            set
            {
                if (!Equals(_startType, value))
                {
                    _startType = value;
                    AddModifiedProperty(nameof(StartType));
                }
            }
        }

        [NonSerialized] private int? _startPar1;
        [ColumnName("START_PAR1")]
        public int? StartPar1
        {
            get => _startPar1;
            set
            {
                if (!Equals(_startPar1, value))
                {
                    _startPar1 = value;
                    AddModifiedProperty(nameof(StartPar1));
                }
            }
        }

        [NonSerialized] private long? _startPar2;
        [ColumnName("START_PAR2")]
        public long? StartPar2
        {
            get => _startPar2;
            set
            {
                if (!Equals(_startPar2, value))
                {
                    _startPar2 = value;
                    AddModifiedProperty(nameof(StartPar2));
                }
            }
        }

        [NonSerialized] private int? _startPar3;
        [ColumnName("START_PAR3")]
        public int? StartPar3
        {
            get => _startPar3;
            set
            {
                if (!Equals(_startPar3, value))
                {
                    _startPar3 = value;
                    AddModifiedProperty(nameof(StartPar3));
                }
            }
        }

        [NonSerialized] private int? _startPar4;
        [ColumnName("START_PAR4")]
        public int? StartPar4
        {
            get => _startPar4;
            set
            {
                if (!Equals(_startPar4, value))
                {
                    _startPar4 = value;
                    AddModifiedProperty(nameof(StartPar4));
                }
            }
        }

        [NonSerialized] private int? _destType;
        [ColumnName("DEST_TYPE")]
        public int? DestType
        {
            get => _destType;
            set
            {
                if (!Equals(_destType, value))
                {
                    _destType = value;
                    AddModifiedProperty(nameof(DestType));
                }
            }
        }

        [NonSerialized] private int? _destPar1;
        [ColumnName("DEST_PAR1")]
        public int? DestPar1
        {
            get => _destPar1;
            set
            {
                if (!Equals(_destPar1, value))
                {
                    _destPar1 = value;
                    AddModifiedProperty(nameof(DestPar1));
                }
            }
        }

        [NonSerialized] private int? _destPar2;
        [ColumnName("DEST_PAR2")]
        public int? DestPar2
        {
            get => _destPar2;
            set
            {
                if (!Equals(_destPar2, value))
                {
                    _destPar2 = value;
                    AddModifiedProperty(nameof(DestPar2));
                }
            }
        }

        [NonSerialized] private int? _destPar3;
        [ColumnName("DEST_PAR3")]
        public int? DestPar3
        {
            get => _destPar3;
            set
            {
                if (!Equals(_destPar3, value))
                {
                    _destPar3 = value;
                    AddModifiedProperty(nameof(DestPar3));
                }
            }
        }

        [NonSerialized] private int? _destPar4;
        [ColumnName("DEST_PAR4")]
        public int? DestPar4
        {
            get => _destPar4;
            set
            {
                if (!Equals(_destPar4, value))
                {
                    _destPar4 = value;
                    AddModifiedProperty(nameof(DestPar4));
                }
            }
        }

        [NonSerialized] private int? _actualType;
        [ColumnName("ACTUAL_TYPE")]
        public int? ActualType
        {
            get => _actualType;
            set
            {
                if (!Equals(_actualType, value))
                {
                    _actualType = value;
                    AddModifiedProperty(nameof(ActualType));
                }
            }
        }

        [NonSerialized] private int? _actualPar1;
        [ColumnName("ACTUAL_PAR1")]
        public int? ActualPar1
        {
            get => _actualPar1;
            set
            {
                if (!Equals(_actualPar1, value))
                {
                    _actualPar1 = value;
                    AddModifiedProperty(nameof(ActualPar1));
                }
            }
        }

        [NonSerialized] private int? _actualPar2;
        [ColumnName("ACTUAL_PAR2")]
        public int? ActualPar2
        {
            get => _actualPar2;
            set
            {
                if (!Equals(_actualPar2, value))
                {
                    _actualPar2 = value;
                    AddModifiedProperty(nameof(ActualPar2));
                }
            }
        }

        [NonSerialized] private int? _actualPar3;
        [ColumnName("ACTUAL_PAR3")]
        public int? ActualPar3
        {
            get => _actualPar3;
            set
            {
                if (!Equals(_actualPar3, value))
                {
                    _actualPar3 = value;
                    AddModifiedProperty(nameof(ActualPar3));
                }
            }
        }

        [NonSerialized] private int? _actualPar4;
        [ColumnName("ACTUAL_PAR4")]
        public int? ActualPar4
        {
            get => _actualPar4;
            set
            {
                if (!Equals(_actualPar4, value))
                {
                    _actualPar4 = value;
                    AddModifiedProperty(nameof(ActualPar4));
                }
            }
        }

        [NonSerialized] private int? _priority;
        [ColumnName("PRIORITY")]
        public int? Priority
        {
            get => _priority;
            set
            {
                if (!Equals(_priority, value))
                {
                    _priority = value;
                    AddModifiedProperty(nameof(Priority));
                }
            }
        }

        [NonSerialized] private int? _finished;
        [ColumnName("FINISHED")]
        public int? Finished
        {
            get => _finished;
            set
            {
                if (!Equals(_finished, value))
                {
                    _finished = value;
                    AddModifiedProperty(nameof(Finished));
                }
            }
        }

        [NonSerialized] private int? _result;
        [ColumnName("RESULT")]
        public int? Result
        {
            get => _result;
            set
            {
                if (!Equals(_result, value))
                {
                    _result = value;
                    AddModifiedProperty(nameof(Result));
                }
            }
        }

        [NonSerialized] private string _constraint = "";
        [ColumnName("CONSTRAINT")]
        public string Constraint
        {
            get => _constraint;
            set
            {
                if (!Equals(_constraint, value))
                {
                    _constraint = value;
                    AddModifiedProperty(nameof(Constraint));
                }
            }
        }

        [NonSerialized] private int? _roundBack;
        [ColumnName("ROUND_BACK")]
        public int? RoundBack
        {
            get => _roundBack;
            set
            {
                if (!Equals(_roundBack, value))
                {
                    _roundBack = value;
                    AddModifiedProperty(nameof(RoundBack));
                }
            }
        }

        [NonSerialized] private DateTime? _dtStart;
        [ColumnName("DT_START")]
        public DateTime? DtStart
        {
            get => _dtStart;
            set
            {
                if (!Equals(_dtStart, value))
                {
                    _dtStart = value;
                    AddModifiedProperty(nameof(DtStart));
                }
            }
        }

        [NonSerialized] private DateTime? _dtInsert;
        [ColumnName("DT_INSERT")]
        public DateTime? DtInsert
        {
            get => _dtInsert;
            set
            {
                if (!Equals(_dtInsert, value))
                {
                    _dtInsert = value;
                    AddModifiedProperty(nameof(DtInsert));
                }
            }
        }

        [NonSerialized] private int? _flCheckPicking;
        [ColumnName("FL_CHECK_PICKING")]
        public int? FlCheckPicking
        {
            get => _flCheckPicking;
            set
            {
                if (!Equals(_flCheckPicking, value))
                {
                    _flCheckPicking = value;
                    AddModifiedProperty(nameof(FlCheckPicking));
                }
            }
        }

        [NonSerialized] private DateTime? _dtUpdate;
        [ColumnName("DT_UPDATE")]
        public DateTime? DtUpdate
        {
            get => _dtUpdate;
            set
            {
                if (!Equals(_dtUpdate, value))
                {
                    _dtUpdate = value;
                    AddModifiedProperty(nameof(DtUpdate));
                }
            }
        }

        [NonSerialized] private string _lastZiItem = "";
        [ColumnName("LAST_ZI_ITEM")]
        public string LastZiItem
        {
            get => _lastZiItem;
            set
            {
                if (!Equals(_lastZiItem, value))
                {
                    _lastZiItem = value;
                    AddModifiedProperty(nameof(LastZiItem));
                }
            }
        }

        [NonSerialized] private int _flMoving = default(int);
        [ColumnName("FL_MOVING")]
        [Required]
        public int FlMoving
        {
            get => _flMoving;
            set
            {
                if (!Equals(_flMoving, value))
                {
                    _flMoving = value;
                    AddModifiedProperty(nameof(FlMoving));
                }
            }
        }

    }
}
