using System;
using System.CodeDom.Compiler;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using DBDataLibrary.Attributes;
using DBDataLibrary.CRUD;

namespace DBDataLibrary.Tables
{
    //  <auto-generated>
    //   -------------------------------------------------- 
    //  |               AUTO-GENERATED CLASS               |
    //  |           -- DO NOT MODIFY MANUALLY! --          |
    //  |  ANY CHANGE WILL BE LOST AT THE NEXT GENERATION  |
    //   -------------------------------------------------- 
    //  </auto-generated>
    [TableName("MFC_CONV_MOV_UDM_MODIFY_DEST")]
    [GeneratedCode("DbDataClassGenerator", "1.0.0.0")]
    public partial class MfcConvMovUdmModifyDest : ACrudBase<MfcConvMovUdmModifyDest>
    {
        public MfcConvMovUdmModifyDest() : base() { }
        
        [NonSerialized] private int? _pos;
        [ColumnName("POS")]
        public int? Pos
        {
            get => _pos;
            set
            {
                if (!Equals(_pos, value))
                {
                    _pos = value;
                    AddModifiedProperty(nameof(Pos));
                }
            }
        }

    }
}
