using System;
using System.CodeDom.Compiler;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using DBDataLibrary.Attributes;
using DBDataLibrary.CRUD;

namespace DBDataLibrary.Tables
{
    //  <auto-generated>
    //   -------------------------------------------------- 
    //  |               AUTO-GENERATED CLASS               |
    //  |           -- DO NOT MODIFY MANUALLY! --          |
    //  |  ANY CHANGE WILL BE LOST AT THE NEXT GENERATION  |
    //   -------------------------------------------------- 
    //  </auto-generated>
    [TableName("MFC_CONV_PROFILE_CHECK_ERROR")]
    [GeneratedCode("DbDataClassGenerator", "1.0.0.0")]
    public partial class MfcConvProfileCheckError : ACrudBase<MfcConvProfileCheckError>
    {
        public MfcConvProfileCheckError() : base() { }
        
        [NonSerialized] private int _cdError = default(int);
        [ColumnName("CD_ERROR")]
        [Required]
        public int CdError
        {
            get => _cdError;
            set
            {
                if (!Equals(_cdError, value))
                {
                    _cdError = value;
                    AddModifiedProperty(nameof(CdError));
                }
            }
        }

        [NonSerialized] private string _dscError = "";
        [ColumnName("DSC_ERROR")]
        [Required]
        public string DscError
        {
            get => _dscError;
            set
            {
                if (!Equals(_dscError, value))
                {
                    _dscError = value;
                    AddModifiedProperty(nameof(DscError));
                }
            }
        }

    }
}
