using System;
using System.CodeDom.Compiler;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using DBDataLibrary.Attributes;
using DBDataLibrary.CRUD;

namespace DBDataLibrary.Tables
{
    //  <auto-generated>
    //   -------------------------------------------------- 
    //  |               AUTO-GENERATED CLASS               |
    //  |           -- DO NOT MODIFY MANUALLY! --          |
    //  |  ANY CHANGE WILL BE LOST AT THE NEXT GENERATION  |
    //   -------------------------------------------------- 
    //  </auto-generated>
    [TableName("MFC_CONV_EMPTY_LINE")]
    [GeneratedCode("DbDataClassGenerator", "1.0.0.0")]
    public partial class MfcConvEmptyLine : ACrudBase<MfcConvEmptyLine>
    {
        public MfcConvEmptyLine() : base() { }
        
        [NonSerialized] private int _cdLine = default(int);
        [ColumnName("CD_LINE")]
        [Required]
        public int CdLine
        {
            get => _cdLine;
            set
            {
                if (!Equals(_cdLine, value))
                {
                    _cdLine = value;
                    AddModifiedProperty(nameof(CdLine));
                }
            }
        }

        [NonSerialized] private string _dscLine = "";
        [ColumnName("DSC_LINE")]
        public string DscLine
        {
            get => _dscLine;
            set
            {
                if (!Equals(_dscLine, value))
                {
                    _dscLine = value;
                    AddModifiedProperty(nameof(DscLine));
                }
            }
        }

        [NonSerialized] private int? _tpUdm;
        [ColumnName("TP_UDM")]
        public int? TpUdm
        {
            get => _tpUdm;
            set
            {
                if (!Equals(_tpUdm, value))
                {
                    _tpUdm = value;
                    AddModifiedProperty(nameof(TpUdm));
                }
            }
        }

        [NonSerialized] private int? _enable;
        [ColumnName("ENABLE")]
        public int? Enable
        {
            get => _enable;
            set
            {
                if (!Equals(_enable, value))
                {
                    _enable = value;
                    AddModifiedProperty(nameof(Enable));
                }
            }
        }

        [NonSerialized] private int? _autoExtractionEnabled;
        [ColumnName("AUTO_EXTRACTION_ENABLED")]
        public int? AutoExtractionEnabled
        {
            get => _autoExtractionEnabled;
            set
            {
                if (!Equals(_autoExtractionEnabled, value))
                {
                    _autoExtractionEnabled = value;
                    AddModifiedProperty(nameof(AutoExtractionEnabled));
                }
            }
        }

    }
}
