using System;
using System.CodeDom.Compiler;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using DBDataLibrary.Attributes;
using DBDataLibrary.CRUD;

namespace DBDataLibrary.Tables
{
    //  <auto-generated>
    //   -------------------------------------------------- 
    //  |               AUTO-GENERATED CLASS               |
    //  |           -- DO NOT MODIFY MANUALLY! --          |
    //  |  ANY CHANGE WILL BE LOST AT THE NEXT GENERATION  |
    //   -------------------------------------------------- 
    //  </auto-generated>
    [TableName("MFC_CONV_ERROR")]
    [GeneratedCode("DbDataClassGenerator", "1.0.0.0")]
    public partial class MfcConvError : ACrudBase<MfcConvError>
    {
        public MfcConvError() : base() { }
        
        [NonSerialized] private int? _cdError;
        [ColumnName("CD_ERROR")]
        public int? CdError
        {
            get => _cdError;
            set
            {
                if (!Equals(_cdError, value))
                {
                    _cdError = value;
                    AddModifiedProperty(nameof(CdError));
                }
            }
        }

        [NonSerialized] private int? _cdConveyor;
        [ColumnName("CD_CONVEYOR")]
        public int? CdConveyor
        {
            get => _cdConveyor;
            set
            {
                if (!Equals(_cdConveyor, value))
                {
                    _cdConveyor = value;
                    AddModifiedProperty(nameof(CdConveyor));
                }
            }
        }

        [NonSerialized] private string _cdLanguage = "";
        [ColumnName("CD_LANGUAGE")]
        public string CdLanguage
        {
            get => _cdLanguage;
            set
            {
                if (!Equals(_cdLanguage, value))
                {
                    _cdLanguage = value;
                    AddModifiedProperty(nameof(CdLanguage));
                }
            }
        }

        [NonSerialized] private string _dscError = "";
        [ColumnName("DSC_ERROR")]
        public string DscError
        {
            get => _dscError;
            set
            {
                if (!Equals(_dscError, value))
                {
                    _dscError = value;
                    AddModifiedProperty(nameof(DscError));
                }
            }
        }

        [NonSerialized] private long? _oidMfcDatablock;
        [ColumnName("OID_MFC_DATABLOCK")]
        public long? OidMfcDatablock
        {
            get => _oidMfcDatablock;
            set
            {
                if (!Equals(_oidMfcDatablock, value))
                {
                    _oidMfcDatablock = value;
                    AddModifiedProperty(nameof(OidMfcDatablock));
                }
            }
        }

        [NonSerialized] private long? _bitPosition;
        [ColumnName("BIT_POSITION")]
        public long? BitPosition
        {
            get => _bitPosition;
            set
            {
                if (!Equals(_bitPosition, value))
                {
                    _bitPosition = value;
                    AddModifiedProperty(nameof(BitPosition));
                }
            }
        }

        [NonSerialized] private int? _tpAnomaly;
        [ColumnName("TP_ANOMALY")]
        public int? TpAnomaly
        {
            get => _tpAnomaly;
            set
            {
                if (!Equals(_tpAnomaly, value))
                {
                    _tpAnomaly = value;
                    AddModifiedProperty(nameof(TpAnomaly));
                }
            }
        }

    }
}
