using System;
using System.CodeDom.Compiler;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using DBDataLibrary.Attributes;
using DBDataLibrary.CRUD;

namespace DBDataLibrary.Tables
{
    //  <auto-generated>
    //   -------------------------------------------------- 
    //  |               AUTO-GENERATED CLASS               |
    //  |           -- DO NOT MODIFY MANUALLY! --          |
    //  |  ANY CHANGE WILL BE LOST AT THE NEXT GENERATION  |
    //   -------------------------------------------------- 
    //  </auto-generated>
    [TableName("MFC_CONV_TRACKING")]
    [GeneratedCode("DbDataClassGenerator", "1.0.0.0")]
    public partial class MfcConvTracking : ACrudBase<MfcConvTracking>
    {
        public MfcConvTracking() : base() { }
        
        [NonSerialized] private long? _oidUdm;
        [ColumnName("OID_UDM")]
        public long? OidUdm
        {
            get => _oidUdm;
            set
            {
                if (!Equals(_oidUdm, value))
                {
                    _oidUdm = value;
                    AddModifiedProperty(nameof(OidUdm));
                }
            }
        }

        [NonSerialized] private string _cdItem = "";
        [ColumnName("CD_ITEM")]
        [Key]
        public string CdItem
        {
            get => _cdItem;
            set
            {
                if (!Equals(_cdItem, value))
                {
                    _cdItem = value;
                    AddModifiedProperty(nameof(CdItem));
                }
            }
        }

        [NonSerialized] private string _cdGroup = "";
        [ColumnName("CD_GROUP")]
        public string CdGroup
        {
            get => _cdGroup;
            set
            {
                if (!Equals(_cdGroup, value))
                {
                    _cdGroup = value;
                    AddModifiedProperty(nameof(CdGroup));
                }
            }
        }

        [NonSerialized] private int _posOccupied = default(int);
        [ColumnName("POS_OCCUPIED")]
        [Required]
        public int PosOccupied
        {
            get => _posOccupied;
            set
            {
                if (!Equals(_posOccupied, value))
                {
                    _posOccupied = value;
                    AddModifiedProperty(nameof(PosOccupied));
                }
            }
        }

        [NonSerialized] private int _aMessage = default(int);
        [ColumnName("A_MESSAGE")]
        [Required]
        public int AMessage
        {
            get => _aMessage;
            set
            {
                if (!Equals(_aMessage, value))
                {
                    _aMessage = value;
                    AddModifiedProperty(nameof(AMessage));
                }
            }
        }

        [NonSerialized] private DateTime? _dtUpdate;
        [ColumnName("DT_UPDATE")]
        public DateTime? DtUpdate
        {
            get => _dtUpdate;
            set
            {
                if (!Equals(_dtUpdate, value))
                {
                    _dtUpdate = value;
                    AddModifiedProperty(nameof(DtUpdate));
                }
            }
        }

    }
}
