using System;
using System.CodeDom.Compiler;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using DBDataLibrary.Attributes;
using DBDataLibrary.CRUD;

namespace DBDataLibrary.Tables
{
    //  <auto-generated>
    //   -------------------------------------------------- 
    //  |               AUTO-GENERATED CLASS               |
    //  |           -- DO NOT MODIFY MANUALLY! --          |
    //  |  ANY CHANGE WILL BE LOST AT THE NEXT GENERATION  |
    //   -------------------------------------------------- 
    //  </auto-generated>
    [TableName("MFC_CONV_CROSS")]
    [GeneratedCode("DbDataClassGenerator", "1.0.0.0")]
    public partial class MfcConvCross : ACrudBase<MfcConvCross>
    {
        public MfcConvCross() : base() { }
        
        [NonSerialized] private string _cdCross = "";
        [ColumnName("CD_CROSS")]
        [Required]
        public string CdCross
        {
            get => _cdCross;
            set
            {
                if (!Equals(_cdCross, value))
                {
                    _cdCross = value;
                    AddModifiedProperty(nameof(CdCross));
                }
            }
        }

        [NonSerialized] private string _first = "";
        [ColumnName("FIRST")]
        [Required]
        public string First
        {
            get => _first;
            set
            {
                if (!Equals(_first, value))
                {
                    _first = value;
                    AddModifiedProperty(nameof(First));
                }
            }
        }

        [NonSerialized] private string _second = "";
        [ColumnName("SECOND")]
        [Required]
        public string Second
        {
            get => _second;
            set
            {
                if (!Equals(_second, value))
                {
                    _second = value;
                    AddModifiedProperty(nameof(Second));
                }
            }
        }

        [NonSerialized] private int? _tot;
        [ColumnName("TOT")]
        public int? Tot
        {
            get => _tot;
            set
            {
                if (!Equals(_tot, value))
                {
                    _tot = value;
                    AddModifiedProperty(nameof(Tot));
                }
            }
        }

    }
}
