using System;
using System.CodeDom.Compiler;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using DBDataLibrary.Attributes;
using DBDataLibrary.CRUD;

namespace DBDataLibrary.Tables
{
    //  <auto-generated>
    //   -------------------------------------------------- 
    //  |               AUTO-GENERATED CLASS               |
    //  |           -- DO NOT MODIFY MANUALLY! --          |
    //  |  ANY CHANGE WILL BE LOST AT THE NEXT GENERATION  |
    //   -------------------------------------------------- 
    //  </auto-generated>
    [TableName("MFC_CONV_MAN_TO_COM")]
    [GeneratedCode("DbDataClassGenerator", "1.0.0.0")]
    public partial class MfcConvManToCom : ACrudBase<MfcConvManToCom>
    {
        public MfcConvManToCom() : base() { }
        
        [NonSerialized] private long _oid = default(long);
        [ColumnName("OID")]
        [Key]
        public long Oid
        {
            get => _oid;
            set
            {
                if (!Equals(_oid, value))
                {
                    _oid = value;
                    AddModifiedProperty(nameof(Oid));
                }
            }
        }

        [NonSerialized] private string _message = "";
        [ColumnName("MESSAGE")]
        [Required]
        public string Message
        {
            get => _message;
            set
            {
                if (!Equals(_message, value))
                {
                    _message = value;
                    AddModifiedProperty(nameof(Message));
                }
            }
        }

        [NonSerialized] private string _localEndpointCode = "";
        [ColumnName("LOCAL_ENDPOINT_CODE")]
        public string LocalEndpointCode
        {
            get => _localEndpointCode;
            set
            {
                if (!Equals(_localEndpointCode, value))
                {
                    _localEndpointCode = value;
                    AddModifiedProperty(nameof(LocalEndpointCode));
                }
            }
        }

        [NonSerialized] private string _remoteEndpointCode = "";
        [ColumnName("REMOTE_ENDPOINT_CODE")]
        public string RemoteEndpointCode
        {
            get => _remoteEndpointCode;
            set
            {
                if (!Equals(_remoteEndpointCode, value))
                {
                    _remoteEndpointCode = value;
                    AddModifiedProperty(nameof(RemoteEndpointCode));
                }
            }
        }

        [NonSerialized] private DateTime _dtInsert = DateTime.MinValue;
        [ColumnName("DT_INSERT")]
        [Required]
        public DateTime DtInsert
        {
            get => _dtInsert;
            set
            {
                if (!Equals(_dtInsert, value))
                {
                    _dtInsert = value;
                    AddModifiedProperty(nameof(DtInsert));
                }
            }
        }

    }
}
