using System;
using System.CodeDom.Compiler;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using DBDataLibrary.Attributes;
using DBDataLibrary.CRUD;

namespace DBDataLibrary.Tables
{
    //  <auto-generated>
    //   -------------------------------------------------- 
    //  |               AUTO-GENERATED CLASS               |
    //  |           -- DO NOT MODIFY MANUALLY! --          |
    //  |  ANY CHANGE WILL BE LOST AT THE NEXT GENERATION  |
    //   -------------------------------------------------- 
    //  </auto-generated>
    [TableName("MFC_CONV_FIFO")]
    [GeneratedCode("DbDataClassGenerator", "1.0.0.0")]
    public partial class MfcConvFifo : ACrudBase<MfcConvFifo>
    {
        public MfcConvFifo() : base() { }
        
        [NonSerialized] private int? _cdFifo;
        [ColumnName("CD_FIFO")]
        public int? CdFifo
        {
            get => _cdFifo;
            set
            {
                if (!Equals(_cdFifo, value))
                {
                    _cdFifo = value;
                    AddModifiedProperty(nameof(CdFifo));
                }
            }
        }

        [NonSerialized] private DateTime? _dtInsert;
        [ColumnName("DT_INSERT")]
        public DateTime? DtInsert
        {
            get => _dtInsert;
            set
            {
                if (!Equals(_dtInsert, value))
                {
                    _dtInsert = value;
                    AddModifiedProperty(nameof(DtInsert));
                }
            }
        }

        [NonSerialized] private long _oidUdm = default(long);
        [ColumnName("OID_UDM")]
        [Required]
        public long OidUdm
        {
            get => _oidUdm;
            set
            {
                if (!Equals(_oidUdm, value))
                {
                    _oidUdm = value;
                    AddModifiedProperty(nameof(OidUdm));
                }
            }
        }

        [NonSerialized] private string _cdUdm = "";
        [ColumnName("CD_UDM")]
        public string CdUdm
        {
            get => _cdUdm;
            set
            {
                if (!Equals(_cdUdm, value))
                {
                    _cdUdm = value;
                    AddModifiedProperty(nameof(CdUdm));
                }
            }
        }

        [NonSerialized] private string _idZone = "";
        [ColumnName("ID_ZONE")]
        [Required]
        public string IdZone
        {
            get => _idZone;
            set
            {
                if (!Equals(_idZone, value))
                {
                    _idZone = value;
                    AddModifiedProperty(nameof(IdZone));
                }
            }
        }

        [NonSerialized] private string _cdUds = "";
        [ColumnName("CD_UDS")]
        public string CdUds
        {
            get => _cdUds;
            set
            {
                if (!Equals(_cdUds, value))
                {
                    _cdUds = value;
                    AddModifiedProperty(nameof(CdUds));
                }
            }
        }

        [NonSerialized] private int _stUds = default(int);
        [ColumnName("ST_UDS")]
        [Required]
        public int StUds
        {
            get => _stUds;
            set
            {
                if (!Equals(_stUds, value))
                {
                    _stUds = value;
                    AddModifiedProperty(nameof(StUds));
                }
            }
        }

        [NonSerialized] private int _plcInc = default(int);
        [ColumnName("PLC_INC")]
        [Required]
        public int PlcInc
        {
            get => _plcInc;
            set
            {
                if (!Equals(_plcInc, value))
                {
                    _plcInc = value;
                    AddModifiedProperty(nameof(PlcInc));
                }
            }
        }

        [NonSerialized] private DateTime? _dtUpdate;
        [ColumnName("DT_UPDATE")]
        public DateTime? DtUpdate
        {
            get => _dtUpdate;
            set
            {
                if (!Equals(_dtUpdate, value))
                {
                    _dtUpdate = value;
                    AddModifiedProperty(nameof(DtUpdate));
                }
            }
        }

        [NonSerialized] private string _plcBarcode = "";
        [ColumnName("PLC_BARCODE")]
        public string PlcBarcode
        {
            get => _plcBarcode;
            set
            {
                if (!Equals(_plcBarcode, value))
                {
                    _plcBarcode = value;
                    AddModifiedProperty(nameof(PlcBarcode));
                }
            }
        }

        [NonSerialized] private string _plcScanner = "";
        [ColumnName("PLC_SCANNER")]
        public string PlcScanner
        {
            get => _plcScanner;
            set
            {
                if (!Equals(_plcScanner, value))
                {
                    _plcScanner = value;
                    AddModifiedProperty(nameof(PlcScanner));
                }
            }
        }

        [NonSerialized] private int? _cdError;
        [ColumnName("CD_ERROR")]
        public int? CdError
        {
            get => _cdError;
            set
            {
                if (!Equals(_cdError, value))
                {
                    _cdError = value;
                    AddModifiedProperty(nameof(CdError));
                }
            }
        }

    }
}
