using System;
using System.CodeDom.Compiler;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using DBDataLibrary.Attributes;
using DBDataLibrary.CRUD;

namespace DBDataLibrary.Tables
{
    //  <auto-generated>
    //   -------------------------------------------------- 
    //  |               AUTO-GENERATED CLASS               |
    //  |           -- DO NOT MODIFY MANUALLY! --          |
    //  |  ANY CHANGE WILL BE LOST AT THE NEXT GENERATION  |
    //   -------------------------------------------------- 
    //  </auto-generated>
    [TableName("MFC_CONV_MOV_ZI_REQUEST")]
    [GeneratedCode("DbDataClassGenerator", "1.0.0.0")]
    public partial class MfcConvMovZiRequest : ACrudBase<MfcConvMovZiRequest>
    {
        public MfcConvMovZiRequest() : base() { }
        
        [NonSerialized] private long _oid = default(long);
        [ColumnName("OID")]
        [Required]
        public long Oid
        {
            get => _oid;
            set
            {
                if (!Equals(_oid, value))
                {
                    _oid = value;
                    AddModifiedProperty(nameof(Oid));
                }
            }
        }

        [NonSerialized] private long? _oidMfcConvMovements;
        [ColumnName("OID_MFC_CONV_MOVEMENTS")]
        public long? OidMfcConvMovements
        {
            get => _oidMfcConvMovements;
            set
            {
                if (!Equals(_oidMfcConvMovements, value))
                {
                    _oidMfcConvMovements = value;
                    AddModifiedProperty(nameof(OidMfcConvMovements));
                }
            }
        }

        [NonSerialized] private long? _oidUdm;
        [ColumnName("OID_UDM")]
        public long? OidUdm
        {
            get => _oidUdm;
            set
            {
                if (!Equals(_oidUdm, value))
                {
                    _oidUdm = value;
                    AddModifiedProperty(nameof(OidUdm));
                }
            }
        }

        [NonSerialized] private int? _oldPos;
        [ColumnName("OLD_POS")]
        public int? OldPos
        {
            get => _oldPos;
            set
            {
                if (!Equals(_oldPos, value))
                {
                    _oldPos = value;
                    AddModifiedProperty(nameof(OldPos));
                }
            }
        }

        [NonSerialized] private int? _newPos;
        [ColumnName("NEW_POS")]
        public int? NewPos
        {
            get => _newPos;
            set
            {
                if (!Equals(_newPos, value))
                {
                    _newPos = value;
                    AddModifiedProperty(nameof(NewPos));
                }
            }
        }

        [NonSerialized] private int? _deleteUdm;
        [ColumnName("DELETE_UDM")]
        public int? DeleteUdm
        {
            get => _deleteUdm;
            set
            {
                if (!Equals(_deleteUdm, value))
                {
                    _deleteUdm = value;
                    AddModifiedProperty(nameof(DeleteUdm));
                }
            }
        }

        [NonSerialized] private int? _flElaborate;
        [ColumnName("FL_ELABORATE")]
        public int? FlElaborate
        {
            get => _flElaborate;
            set
            {
                if (!Equals(_flElaborate, value))
                {
                    _flElaborate = value;
                    AddModifiedProperty(nameof(FlElaborate));
                }
            }
        }

        [NonSerialized] private DateTime? _dtInsert;
        [ColumnName("DT_INSERT")]
        public DateTime? DtInsert
        {
            get => _dtInsert;
            set
            {
                if (!Equals(_dtInsert, value))
                {
                    _dtInsert = value;
                    AddModifiedProperty(nameof(DtInsert));
                }
            }
        }

    }
}
