using System;
using System.CodeDom.Compiler;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using DBDataLibrary.Attributes;
using DBDataLibrary.CRUD;

namespace DBDataLibrary.Tables
{
    //  <auto-generated>
    //   -------------------------------------------------- 
    //  |               AUTO-GENERATED CLASS               |
    //  |           -- DO NOT MODIFY MANUALLY! --          |
    //  |  ANY CHANGE WILL BE LOST AT THE NEXT GENERATION  |
    //   -------------------------------------------------- 
    //  </auto-generated>
    [TableName("MFC_CONV_EVENT_TYPE")]
    [GeneratedCode("DbDataClassGenerator", "1.0.0.0")]
    public partial class MfcConvEventType : ACrudBase<MfcConvEventType>
    {
        public MfcConvEventType() : base() { }
        
        [NonSerialized] private long _oid = default(long);
        [ColumnName("OID")]
        [Key]
        public long Oid
        {
            get => _oid;
            set
            {
                if (!Equals(_oid, value))
                {
                    _oid = value;
                    AddModifiedProperty(nameof(Oid));
                }
            }
        }

        [NonSerialized] private string _dscType = "";
        [ColumnName("DSC_TYPE")]
        [Required]
        public string DscType
        {
            get => _dscType;
            set
            {
                if (!Equals(_dscType, value))
                {
                    _dscType = value;
                    AddModifiedProperty(nameof(DscType));
                }
            }
        }

        [NonSerialized] private int? _eventGroup;
        [ColumnName("EVENT_GROUP")]
        public int? EventGroup
        {
            get => _eventGroup;
            set
            {
                if (!Equals(_eventGroup, value))
                {
                    _eventGroup = value;
                    AddModifiedProperty(nameof(EventGroup));
                }
            }
        }

        [NonSerialized] private string _descComment = "";
        [ColumnName("DESC_COMMENT")]
        public string DescComment
        {
            get => _descComment;
            set
            {
                if (!Equals(_descComment, value))
                {
                    _descComment = value;
                    AddModifiedProperty(nameof(DescComment));
                }
            }
        }

    }
}
