using System;
using System.CodeDom.Compiler;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using DBDataLibrary.Attributes;
using DBDataLibrary.CRUD;

namespace DBDataLibrary.Tables
{
    //  <auto-generated>
    //   -------------------------------------------------- 
    //  |               AUTO-GENERATED CLASS               |
    //  |           -- DO NOT MODIFY MANUALLY! --          |
    //  |  ANY CHANGE WILL BE LOST AT THE NEXT GENERATION  |
    //   -------------------------------------------------- 
    //  </auto-generated>
    [TableName("MFC_CONV_ROUTING_PLC")]
    [GeneratedCode("DbDataClassGenerator", "1.0.0.0")]
    public partial class MfcConvRoutingPlc : ACrudBase<MfcConvRoutingPlc>
    {
        public MfcConvRoutingPlc() : base() { }
        
        [NonSerialized] private string _cdItemTo = "";
        [ColumnName("CD_ITEM_TO")]
        [Required]
        public string CdItemTo
        {
            get => _cdItemTo;
            set
            {
                if (!Equals(_cdItemTo, value))
                {
                    _cdItemTo = value;
                    AddModifiedProperty(nameof(CdItemTo));
                }
            }
        }

        [NonSerialized] private string _cdItemNext = "";
        [ColumnName("CD_ITEM_NEXT")]
        [Required]
        public string CdItemNext
        {
            get => _cdItemNext;
            set
            {
                if (!Equals(_cdItemNext, value))
                {
                    _cdItemNext = value;
                    AddModifiedProperty(nameof(CdItemNext));
                }
            }
        }

    }
}
