using System;
using System.CodeDom.Compiler;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using DBDataLibrary.Attributes;
using DBDataLibrary.CRUD;

namespace DBDataLibrary.Tables
{
    //  <auto-generated>
    //   -------------------------------------------------- 
    //  |               AUTO-GENERATED CLASS               |
    //  |           -- DO NOT MODIFY MANUALLY! --          |
    //  |  ANY CHANGE WILL BE LOST AT THE NEXT GENERATION  |
    //   -------------------------------------------------- 
    //  </auto-generated>
    [TableName("MFC_CONV_IO_CRANE")]
    [GeneratedCode("DbDataClassGenerator", "1.0.0.0")]
    public partial class MfcConvIoCrane : ACrudBase<MfcConvIoCrane>
    {
        public MfcConvIoCrane() : base() { }
        
        [NonSerialized] private string _cdItem = "";
        [ColumnName("CD_ITEM")]
        [Required]
        public string CdItem
        {
            get => _cdItem;
            set
            {
                if (!Equals(_cdItem, value))
                {
                    _cdItem = value;
                    AddModifiedProperty(nameof(CdItem));
                }
            }
        }

        [NonSerialized] private int _direction = default(int);
        [ColumnName("DIRECTION")]
        [Required]
        public int Direction
        {
            get => _direction;
            set
            {
                if (!Equals(_direction, value))
                {
                    _direction = value;
                    AddModifiedProperty(nameof(Direction));
                }
            }
        }

        [NonSerialized] private int _cdCrane = default(int);
        [ColumnName("CD_CRANE")]
        [Required]
        public int CdCrane
        {
            get => _cdCrane;
            set
            {
                if (!Equals(_cdCrane, value))
                {
                    _cdCrane = value;
                    AddModifiedProperty(nameof(CdCrane));
                }
            }
        }

        [NonSerialized] private int _cdPosHead = default(int);
        [ColumnName("CD_POS_HEAD")]
        [Required]
        public int CdPosHead
        {
            get => _cdPosHead;
            set
            {
                if (!Equals(_cdPosHead, value))
                {
                    _cdPosHead = value;
                    AddModifiedProperty(nameof(CdPosHead));
                }
            }
        }

        [NonSerialized] private int? _coordinateX;
        [ColumnName("COORDINATE_X")]
        public int? CoordinateX
        {
            get => _coordinateX;
            set
            {
                if (!Equals(_coordinateX, value))
                {
                    _coordinateX = value;
                    AddModifiedProperty(nameof(CoordinateX));
                }
            }
        }

        [NonSerialized] private int? _coordinateY;
        [ColumnName("COORDINATE_Y")]
        public int? CoordinateY
        {
            get => _coordinateY;
            set
            {
                if (!Equals(_coordinateY, value))
                {
                    _coordinateY = value;
                    AddModifiedProperty(nameof(CoordinateY));
                }
            }
        }

        [NonSerialized] private int? _coordinateZ;
        [ColumnName("COORDINATE_Z")]
        public int? CoordinateZ
        {
            get => _coordinateZ;
            set
            {
                if (!Equals(_coordinateZ, value))
                {
                    _coordinateZ = value;
                    AddModifiedProperty(nameof(CoordinateZ));
                }
            }
        }

        [NonSerialized] private string _cdItemReject = "";
        [ColumnName("CD_ITEM_REJECT")]
        [Required]
        public string CdItemReject
        {
            get => _cdItemReject;
            set
            {
                if (!Equals(_cdItemReject, value))
                {
                    _cdItemReject = value;
                    AddModifiedProperty(nameof(CdItemReject));
                }
            }
        }

        [NonSerialized] private string _cdItemZi = "";
        [ColumnName("CD_ITEM_ZI")]
        public string CdItemZi
        {
            get => _cdItemZi;
            set
            {
                if (!Equals(_cdItemZi, value))
                {
                    _cdItemZi = value;
                    AddModifiedProperty(nameof(CdItemZi));
                }
            }
        }

        [NonSerialized] private int? _priority;
        [ColumnName("PRIORITY")]
        public int? Priority
        {
            get => _priority;
            set
            {
                if (!Equals(_priority, value))
                {
                    _priority = value;
                    AddModifiedProperty(nameof(Priority));
                }
            }
        }

        [NonSerialized] private string _constraint = "";
        [ColumnName("CONSTRAINT")]
        [Required]
        public string Constraint
        {
            get => _constraint;
            set
            {
                if (!Equals(_constraint, value))
                {
                    _constraint = value;
                    AddModifiedProperty(nameof(Constraint));
                }
            }
        }

        [NonSerialized] private string _cdItemUnload = "";
        [ColumnName("CD_ITEM_UNLOAD")]
        public string CdItemUnload
        {
            get => _cdItemUnload;
            set
            {
                if (!Equals(_cdItemUnload, value))
                {
                    _cdItemUnload = value;
                    AddModifiedProperty(nameof(CdItemUnload));
                }
            }
        }

        [NonSerialized] private string _cdItemLoad = "";
        [ColumnName("CD_ITEM_LOAD")]
        public string CdItemLoad
        {
            get => _cdItemLoad;
            set
            {
                if (!Equals(_cdItemLoad, value))
                {
                    _cdItemLoad = value;
                    AddModifiedProperty(nameof(CdItemLoad));
                }
            }
        }

        [NonSerialized] private int _floor = default(int);
        [ColumnName("FLOOR")]
        [Required]
        public int Floor
        {
            get => _floor;
            set
            {
                if (!Equals(_floor, value))
                {
                    _floor = value;
                    AddModifiedProperty(nameof(Floor));
                }
            }
        }

    }
}
