using System;
using System.CodeDom.Compiler;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using DBDataLibrary.Attributes;
using DBDataLibrary.CRUD;

namespace DBDataLibrary.Tables
{
    //  <auto-generated>
    //   -------------------------------------------------- 
    //  |               AUTO-GENERATED CLASS               |
    //  |           -- DO NOT MODIFY MANUALLY! --          |
    //  |  ANY CHANGE WILL BE LOST AT THE NEXT GENERATION  |
    //   -------------------------------------------------- 
    //  </auto-generated>
    [TableName("FULL_ACCESS_CRUD_TABLE")]
    [GeneratedCode("DbDataClassGenerator", "1.0.0.0")]
    public partial class FullAccessCRUDTable : ACrudBase<FullAccessCRUDTable>
    {
        public FullAccessCRUDTable() : base() { }
        
        [NonSerialized] private string _cdItem = "";
        [ColumnName("CD_ITEM")]
        [Required]
        public string CdItem
        {
            get => _cdItem;
            set
            {
                if (!Equals(_cdItem, value))
                {
                    _cdItem = value;
                    AddModifiedProperty(nameof(CdItem));
                }
            }
        }

        [NonSerialized] private DateTime _dtStart = DateTime.MinValue;
        [ColumnName("DT_START")]
        [Required]
        public DateTime DtStart
        {
            get => _dtStart;
            set
            {
                if (!Equals(_dtStart, value))
                {
                    _dtStart = value;
                    AddModifiedProperty(nameof(DtStart));
                }
            }
        }

        [NonSerialized] private DateTime? _dtEnd;
        [ColumnName("DT_END")]
        public DateTime? DtEnd
        {
            get => _dtEnd;
            set
            {
                if (!Equals(_dtEnd, value))
                {
                    _dtEnd = value;
                    AddModifiedProperty(nameof(DtEnd));
                }
            }
        }

        [NonSerialized] private int _errorCode = default(int);
        [ColumnName("CD_ERROR")]
        [Required]
        public int ErrorCode
        {
            get => _errorCode;
            set
            {
                if (!Equals(_errorCode, value))
                {
                    _errorCode = value;
                    AddModifiedProperty(nameof(ErrorCode));
                }
            }
        }

        [NonSerialized] private int? _errorType;
        [ColumnName("TP_ERROR")]
        public int? ErrorType
        {
            get => _errorType;
            set
            {
                if (!Equals(_errorType, value))
                {
                    _errorType = value;
                    AddModifiedProperty(nameof(ErrorType));
                }
            }
        }

    }
}
