using System;
using System.CodeDom.Compiler;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using DBDataLibrary.Attributes;
using DBDataLibrary.CRUD;

namespace DBDataLibrary.Tables
{
    //  <auto-generated>
    //   -------------------------------------------------- 
    //  |               AUTO-GENERATED CLASS               |
    //  |           -- DO NOT MODIFY MANUALLY! --          |
    //  |  ANY CHANGE WILL BE LOST AT THE NEXT GENERATION  |
    //   -------------------------------------------------- 
    //  </auto-generated>
    [TableName("MFC_CONV_ANOMALIES")]
    [GeneratedCode("DbDataClassGenerator", "1.0.0.0")]
    public partial class MfcConvAnomalies : ACrudBase<MfcConvAnomalies>
    {
        public MfcConvAnomalies() : base() { }
        
        [NonSerialized] private string _cdZone = "";
        [ColumnName("CD_ZONE")]
        [Required]
        public string CdZone
        {
            get => _cdZone;
            set
            {
                if (!Equals(_cdZone, value))
                {
                    _cdZone = value;
                    AddModifiedProperty(nameof(CdZone));
                }
            }
        }

        [NonSerialized] private DateTime _dtStartAnomaly = DateTime.MinValue;
        [ColumnName("DT_START_ANOMALY")]
        [Required]
        public DateTime DtStartAnomaly
        {
            get => _dtStartAnomaly;
            set
            {
                if (!Equals(_dtStartAnomaly, value))
                {
                    _dtStartAnomaly = value;
                    AddModifiedProperty(nameof(DtStartAnomaly));
                }
            }
        }

        [NonSerialized] private DateTime? _dtEndAnomaly;
        [ColumnName("DT_END_ANOMALY")]
        public DateTime? DtEndAnomaly
        {
            get => _dtEndAnomaly;
            set
            {
                if (!Equals(_dtEndAnomaly, value))
                {
                    _dtEndAnomaly = value;
                    AddModifiedProperty(nameof(DtEndAnomaly));
                }
            }
        }

        [NonSerialized] private int _cdError = default(int);
        [ColumnName("CD_ERROR")]
        [Required]
        public int CdError
        {
            get => _cdError;
            set
            {
                if (!Equals(_cdError, value))
                {
                    _cdError = value;
                    AddModifiedProperty(nameof(CdError));
                }
            }
        }

        [NonSerialized] private int? _tpError;
        [ColumnName("TP_ERROR")]
        public int? TpError
        {
            get => _tpError;
            set
            {
                if (!Equals(_tpError, value))
                {
                    _tpError = value;
                    AddModifiedProperty(nameof(TpError));
                }
            }
        }

    }
}
