using System;
using System.CodeDom.Compiler;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using DBDataLibrary.Attributes;
using DBDataLibrary.CRUD;

namespace DBDataLibrary.Tables
{
    //  <auto-generated>
    //   -------------------------------------------------- 
    //  |               AUTO-GENERATED CLASS               |
    //  |           -- DO NOT MODIFY MANUALLY! --          |
    //  |  ANY CHANGE WILL BE LOST AT THE NEXT GENERATION  |
    //   -------------------------------------------------- 
    //  </auto-generated>
    [TableName("UPDATABLE_TABLE")]
    [GeneratedCode("DbDataClassGenerator", "1.0.0.0")]
    public partial class UpdatableTable : ACrudBase<UpdatableTable>
    {
        public UpdatableTable() : base() { }
        
        [NonSerialized] private int _cdItem = default(int);
        [ColumnName("CD_ITEM")]
        [Required]
        public int CdItem
        {
            get => _cdItem;
            set
            {
                if (!Equals(_cdItem, value))
                {
                    _cdItem = value;
                    AddModifiedProperty(nameof(CdItem));
                }
            }
        }

        [NonSerialized] private string _constrain = "";
        [ColumnName("CONSTRAIN")]
        public string Constrain
        {
            get => _constrain;
            set
            {
                if (!Equals(_constrain, value))
                {
                    _constrain = value;
                    AddModifiedProperty(nameof(Constrain));
                }
            }
        }

        [NonSerialized] private int? _stEnabled;
        [ColumnName("ST_ENABLED")]
        public int? StEnabled
        {
            get => _stEnabled;
            set
            {
                if (!Equals(_stEnabled, value))
                {
                    _stEnabled = value;
                    AddModifiedProperty(nameof(StEnabled));
                }
            }
        }

        [NonSerialized] private int? _returnDefaultPosition;
        [ColumnName("RETURN_DEFAULT_POSITION")]
        public int? ReturnDefaultPosition
        {
            get => _returnDefaultPosition;
            set
            {
                if (!Equals(_returnDefaultPosition, value))
                {
                    _returnDefaultPosition = value;
                    AddModifiedProperty(nameof(ReturnDefaultPosition));
                }
            }
        }
    }
}
