// See https://aka.ms/new-console-template for more information
using CRUDTestApp;
using DBDataLibrary.Utils;
using DBDataLibrary.Tables;
using log4net;
using Oracle.ManagedDataAccess.Client;

System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);

log4net.Config.XmlConfigurator.Configure(new FileInfo("log4net.config"));
Directory.CreateDirectory("Logs");

Console.WriteLine("This is just a tiny simple test app for autogenerated CRUD classes");

string connectionString = "Data Source = (DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=172.16.11.218)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=ROEN)));User ID= WMS_ROEN; Password = tabe;Pooling=false;";

DBCrudTester tester = new DBCrudTester(new string[] { "-cs", connectionString });
tester.Run();

Console.WriteLine("Press Enter to exit...");
Console.ReadLine();