// See https://aka.ms/new-console-template for more information
using CRUDTestApp;
using DBDataLibrary.Tables;
using Oracle.ManagedDataAccess.Client;

Console.WriteLine("This is just a tiny simple test app for autogenerated CRUD classes");

string connectionString = "Data Source = (DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=172.16.11.218)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=ROEN)));User ID= WMS_ROEN; Password = tabe;Pooling=false;";

DBCrudTester tester = new DBCrudTester(new string[] { "-cs", connectionString });
tester.Run();

Console.WriteLine("Press Enter to exit...");
Console.ReadLine();