// See https://aka.ms/new-console-template for more information
using CRUDTestApp;

System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);

log4net.Config.XmlConfigurator.Configure(new FileInfo("log4net.config"));
Directory.CreateDirectory("Logs");

Console.WriteLine("This is just a tiny simple test app for autogenerated CRUD classes");

string hostIP = "127.0.0.1";
string serviceName = "ORADB";
string userID = "ORA_USER";
string password = "ORA_PASSWORD";

string connectionString = $"Data Source = (DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST={hostIP})(PORT=1521))(CONNECT_DATA=(SERVICE_NAME={serviceName})));User ID= {userID}; Password = {password};Pooling=false;";

// Check if specific test is requested
if (args.Length > 0 && args[0] == "-testReadOnly")
{
    Console.WriteLine("\n=== Running ReadOnlyOnUpdate Test ===\n");
    var readOnlyTest = new ReadOnlyOnUpdateTest(connectionString);
    readOnlyTest.RunTest();
}
else
{
    DBCrudTester tester = new DBCrudTester(new string[] { "-cs", connectionString });
    tester.Run();
}

Console.WriteLine("Press Enter to exit...");
Console.ReadLine();